### ISSUE TITLE
Plugin API to tell IntelliJ about `grails.artefact.*` traits?

### ISSUE THREAD

**Issue by erichelgeson** [kbialek/idea-grails-plugin#2]
Since recent versions of Grails uses traits for most artefacts is there an API to tell IntelliJ that `class FooController` is actually `class FooController implements Controller`

You can see if I explicitly set this in CE it shows both this plugin and the trait as well:

<img width="533" alt="screen shot 2017-09-23 at 10 16 12 pm" src="https://user-images.githubusercontent.com/271734/30779118-d94be6fe-a0ac-11e7-9c26-5a9b3eeba204.png">

If possible this would reduce the amount of code needed to track what magic grails adds to it's artefacts.

**Comment by kbialek** [comment]
Additional check added to Controller completion and reference providers. Since now the plugin is not enhancing Controller classes implementing grails.artefact.Controller trait anymore.

**Comment by erichelgeson** [comment]
Oh, that's not what I was suggesting (sorry, probably wasn't clear). 

I was suggesting that if there was a way for this plugin to just tell IDEA that any class that ends in *Controller actually had the trait `Controller` then there would be a lot less to code.

(Eg: https://intellij-support.jetbrains.com/hc/en-us/community/posts/206794255-How-to-make-a-PsiClass-derive-from-another-one- - though I just don't know the APIs well enough)

**Comment by kbialek** [comment]
Ok, I see. Sounds interesting. Remaining question is where (in which extension point) such enhancement should be implemented.
